### ISSUE TITLE
Cannot use with npm@7 and monaco-editor@0.27

### ISSUE THREAD

**Issue by 4eb0da** [chengcyber/rollup-plugin-monaco-editor#11]
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: war3-model@2.0.0
npm ERR! Found: monaco-editor@0.27.0
npm ERR! node_modules/monaco-editor
npm ERR!   dev monaco-editor@"0.27.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer monaco-editor@"^0.21.2" from rollup-plugin-monaco-editor@0.1.2
npm ERR! node_modules/rollup-plugin-monaco-editor
npm ERR!   dev rollup-plugin-monaco-editor@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by chengcyber** [comment]
I think this issue comes from npm@7 breaking change about peer dependencies resolution. For now, it seems to me `rollup-plugin-monaco-editor` could hardly help. Since this package should declare the minimal support version of `monaco-editor` which is `^0.21.0`, and `0.27.0` in your project is satisfied with this declartion. I have no idea why npm complain about this.

Possible workaround:
Use `npm install --force` to install dependencies

See https://stackoverflow.com/a/66608842 to get more info about `--force` and `--legacy-peer-deps`

Closing
